In [36]:
import pandas as pd
import numpy as np

#read in rooms
rooms = pd.read_csv("C:/Users/jgerhartz/projects/survey_wiz/static/csv/rooms.csv")
rooms.head()

#read in building code
code = pd.read_csv("building_codes.csv")

In [65]:
#extract room number from room col
rooms['room_num'] = rooms["Room"].str.extract(r'([0-4][0-9][0-9])')

#merge building code to rooms df
rooms_merge = rooms.merge(code, how='left', on='Building')

#create building code col
rooms_merge['building_code'] = rooms_merge['Code'] + rooms_merge['room_num']


                           
#create list of bad rows
olin_auditorium_bool = rooms_merge['Room'].str.contains('Olin Auditorium')
musser_auditorium_bool = rooms_merge['Room'].str.contains('Musser Auditorium')
blackbox_bool = rooms_merge['Room'].str.contains('Kaleidoscope Blackbox Studio Theater')
kal_bool = rooms_merge['Room'].str.contains('Kaleidoscope Lenfest Theater')
lab_bool = rooms_merge['Room'].str.contains('Lab')
delete_bool = olin_auditorium_bool | blackbox_bool | lab_bool | musser_auditorium_bool | kal_bool

#create df of rows to delete
delete_rows = rooms_merge[delete_bool].index

#delete rows
dropped = rooms_merge.drop(delete_rows, axis = 0)

#create list of good cols
data_cols = ['building_code', 'Reservation Hours']

#create df with only good cols
data = dropped[data_cols]

In [66]:
data

   building_code  Reservation Hours
0         BER016             174.08
1         BOM133               9.75
2         BOM306             208.08
3         BOM011             201.17
4         BOM016               0.00
5         BOM128             235.25
6         BOM129             256.25
7         BOM202             251.50
8         BOM228             347.25
9         BOM033             269.92
10        HEL201             245.00
11        HEL204             275.00
12        HEL208             182.25
13        IDC114             219.50
14        IDC116             385.75
15        IDC210             140.83
16        IDC312             124.83
19        KAL142             248.25
20        KAL215              81.67
21        KAL207             119.17
22        MYR201             116.25
24        OLI107              57.08
25        OLI101             331.33
26        OLI102             340.92
27        OLI103             213.42
28        OLI108             333.17
29        OLI004             188.83
30        OLI007             186.92
31        OLI008             186.67
32        OLI009             259.33
33        OLI201             344.83
34        OLI301             275.67
35        OLI303             270.75
37         PF109             244.17
38         PF007             182.00
39         PF012             191.67
40         PF106             294.00
41         PF107             294.00
42         PF201              41.67
43         PF207             236.92
44         PF208             296.67
45         PF209             387.00
46         PF210             457.50
47         PF001             130.67
48         PF013              39.67
49         PF316               0.00
50        RIT202              93.33
51        RIT210              70.00
52        RIT141             261.33
53        RIT203               0.00
54        RIT213              42.00
55        RIT214              84.00

## Clean/Reformat Data Output

In [ ]:
#create hours per week col
rooms['Hours/Week'] = rooms['Reservation Hours']/20

#create bookings/week col 
rooms['Bookings/Week'] = rooms['Booking Count']/20


#select only necessary cols
room_cols = ['Building','Room','Hours/Week']

#create df with important cols
data = rooms[room_cols]

In [ ]:
rooms.to_csv("room_occupancy.csv")

In [ ]:
data.to_csv("classroom_occupancy.csv")

In [ ]:
data